# Custom values for kube-prometheus-stack Helm chart
# Refer to the official chart documentation for all available options:
# https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

# Example: Disable Grafana if you want to manage it separately
# grafana:
#   enabled: false

# Example: Adjust resource requests/limits for Prometheus
# prometheus:
#   prometheusSpec:
#     resources:
#       requests:
#         cpu: 200m
#         memory: 512Mi
#       limits:
#         cpu: 1
#         memory: 2Gi
