apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress-test
  namespace: default
  labels:
    app: cpu-stress-test
    tier: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-stress-test
  template:
    metadata:
      labels:
        app: cpu-stress-test
    spec:
      containers:
      - name: cpu-stress
        image: polinux/stress
        imagePullPolicy: IfNotPresent
        command: ["stress"]
        # Start 2 CPU-bound processes, which will exceed our 100m limit
        args: ["--cpu", "2", "--timeout", "300s"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
