apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: default
  labels:
    app: echo
    tier: dev
spec:
  selector:
    app: echo
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
