apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-stress-test
  namespace: default
  labels:
    app: memory-stress-test
    tier: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-stress-test
  template:
    metadata:
      labels:
        app: memory-stress-test
    spec:
      containers:
      - name: memory-stress
        image: polinux/stress
        imagePullPolicy: IfNotPresent
        command: ["stress"]
        # Allocate 150MB of memory, which exceeds our 128MB limit
        args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "0"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
