apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
  namespace: default
  labels:
    app: metrics
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
        tier: frontend
    spec:
      containers:
      - name: metrics
        image: metrics:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: REACT_APP_PROMETHEUS_URL
          value: "http://prometheus.monitoring.svc.cluster.local:9090/api/v1"
        - name: REACT_APP_USE_MOCK_DATA
          value: "false"
