apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: default
  labels:
    app: metrics
    tier: frontend
spec:
  selector:
    app: metrics
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP
