apiVersion: v1
kind: Service
metadata:
  name: thumb
  namespace: default
  labels:
    app: thumb
    tier: dev
spec:
  selector:
    app: thumb
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
