apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-worker
  namespace: default
  labels:
    app: batch
    component: worker
    tier: standard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: batch
      component: worker
  template:
    metadata:
      labels:
        app: batch
        component: worker
    spec:
      containers:
      - name: batch-worker
        image: batch:latest
        imagePullPolicy: IfNotPresent
        command: ["celery", "-A", "celery_worker", "worker", "--loglevel=info"]
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 400m
            memory: 512Mi
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: uploads
        emptyDir: {}
