apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
  namespace: default
  labels:
    app: metrics
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
        tier: frontend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - metrics
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: metrics
        image: metrics:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        env:
        - name: REACT_APP_PROMETHEUS_URL
          value: "http://prometheus.monitoring.svc.cluster.local:9090/api/v1"
        - name: REACT_APP_USE_MOCK_DATA
          value: "false"
