apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener
  namespace: default
  labels:
    app: shortener
    tier: ha
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shortener
  template:
    metadata:
      labels:
        app: shortener
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - shortener
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: shortener
        image: shortener:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 400m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /shorten
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /shorten
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
