apiVersion: v1
kind: Service
metadata:
  name: shortener
  namespace: default
  labels:
    app: shortener
    tier: ha
spec:
  selector:
    app: shortener
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
