apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumb
  namespace: default
  labels:
    app: thumb
    tier: ha
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thumb
  template:
    metadata:
      labels:
        app: thumb
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - thumb
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: thumb
        image: thumb:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 400m
            memory: 512Mi
          limits:
            cpu: 800m
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
